rvm:
  - 2.1.1

before_install: gem update --remote bundler

before_script:
  - "cp config/database.sample.yml config/database.yml"
  - "psql -c 'create role neighborly SUPERUSER LOGIN;' postgres"
  - "psql -c 'create database neighborly_test;' -U neighborly postgres"
  - "sh -e /etc/init.d/xvfb start"
  - "bundle exec rake db:migrate"
  - "RAILS_ENV=test bundle exec rake spec:javascript"

env:
  - DISPLAY=:99.0

script:
  - "bundle exec rspec spec"

deploy:
  provider: heroku
  api_key:
    secure: t3BCcO2UHJ20lfJEgBqn82Jz8xlof9bsHBJ9ELSEdKQUvRNq/j2mqHMy/EEoE7FgV57FG4jzeHXQqMn39LfQzryLhBuw5cR6a/cu7i0bCwP407CwvVhMCYgIu+eyFx3gXQv0RmfbGdAfrawcA63lSYM6R1eKziX1qFfwYW4W6wI=
  app: neighborly-staging
  run:
    - "rake db:migrate"
    - restart
  on:
    repo: neighborly/neighborly
