language: ruby
rvm:
  - 2.1.1
cache: bundler
env: RAILS_ENV=test DISPLAY=:99.0
script:
  - bundle exec rake spec:javascript
  - bundle exec rspec
before_script:
  - 'psql -c "create role neighborly SUPERUSER LOGIN;" postgres'
  - 'psql -c "create database neighborly_test;" -U neighborly postgres'
  - 'sh -e /etc/init.d/xvfb start'
  - './bin/bootstrap'
deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: tWSfGLGVFh1VPJxIlHzA+iVM8qjDsqmw+eQx0t3//pNJXCpSatS98Dzr8u/W8JXQlMH4mauKfFEVdIKmOQHLfi/yIFIxgjM4CrHOXgDZ7ZtXpzY5NiwUt7eXiCKdWalLmmkdt4vBL9GYTCuGk47HD9cRL8L6jySGxxgjV5zIYTg=
  app: neighborly-staging
  on:
    repo: neighborly/neighborly
  run:
    - rake db:migrate
    - restart
